#!/bin/csh
#
#  C-shell script to execute GAMESS test jobs, one job after the next.
#  Each output is put in its own separate log file in the gamess root.
#  Invoke this by typing 'runall &'.
#
#  A script to check the results is ~/gamess/tools/checktst/checktst
#  Edit this file to set the base path to GAMESS, then execute it to be
#  sure all tests TERMINATED NORMALLY, and got correct numbers too.
#
#  Only the following two lines need to be customized:
#
set VERNO=00
#
#  Loop over all Ntest jobs supplied with GAMESS
#  The jobs are run in batch queues if a very old batch queue program
#  named DQS is found on the system, that's for Iowa State's group,
#  otherwise the test is executed interactively by 'rungms'.
#
set i=1
set Ntest=44
setenv PBS_NODEFILE ./nodes
cat > nodes <<EOF
`hostname`
EOF
while ($i <= $Ntest)
               set NUM=$i
  echo "RUNNING TEST $NUM"
  if ($i <= 9) set NUM=0$i
  if (-e /usr/local/bin/dqs_execd) then
     gms -v $VERNO -q ti -l exam$NUM.log exam$NUM
     sleep 5
  else
     /opt/gamess/rungms exam$NUM $VERNO 1  >&  exam$NUM.log
  endif
  @ i++
end
set num_right=`cat *.log|grep -c 'TERMINATED NORMALLY'`
echo "$num_right tests passed out of $Ntest"
